# -*- coding: utf-8 -*-
"""List-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e2w_ySBbuD6vd-9kde_Av4tF-Sjpchwl
"""

winter = [["Dec", 31], ["Jan", 31], ["Feb", 28]]
summer = [["Jun", 30], ["July", 31], ["Aug", 31]]
autumn = [["Sep", 30], ["Oct", 31], ["Nov", 30]]
spring = [["Mar", 31], ["Apr", 30], ["May", 31]]

print("Summer has", int(summer[0][1] + summer[1][1] + summer[2][1]), "days in a year.")