# -*- coding: utf-8 -*-
"""List-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e2w_ySBbuD6vd-9kde_Av4tF-Sjpchwl
"""

names = ["David", "Michael", "John", "James", "Greg", "Mark", "William", 
          "Richard", "Thomas", "Steven", "Mary", "Susan", "Maria", "Karen", 
          "Lisa", "Linda", "Donna", "Patricia", "Debra", "Eric"]

scores = [99, 87, 78, 86, 68, 94, 76, 97, 56, 98, 76, 87, 79, 90, 73, 93, 82,
           69, 97, 98]
 
student = str(input("Enter the name of student : "))
point = names.index(student)
print("The score of", student, "is", scores[point])