# -*- coding: utf-8 -*-
"""List-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e2w_ySBbuD6vd-9kde_Av4tF-Sjpchwl
"""

my_list = [34, 56, 76, 45, 2, 12, 67, 98, 37, 54, 66]
my_list.sort()
say = int(len(my_list))
toplam = int(my_list[1]) + int(my_list[say-1])
print(toplam)