# -*- coding: utf-8 -*-
"""List-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e2w_ySBbuD6vd-9kde_Av4tF-Sjpchwl
"""

scores = [99, 87, 78, 86, 68, 94, 76, 97 ,56, 98, 76, 87, 79, 90, 73, 93, 82, 69, 97, 98]
scores.sort()
max_score = scores[len(scores)-1]
num_max_score = scores.count(max_score)
print("Max score is", max_score, "and", num_max_score, "student(s) got this point")